### ISSUE TITLE
CSV export include status? How? Configurable?

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#204]
Currently the table exports do not include vip, pool, or member status. If we add them, what should they look like? Should it be configurable?

I guess we could add a preferences setting, or we could have a second CSV button. Thoughts?

**Comment by epacke** [comment]
I'm thinking that adding/removing column in the csv/excel files should be easy enough and avoiding a config just for this would result in less clutter. Do you agree?

**Comment by timriker** [comment]
We have multiple status indications. virtual server, pool, and member. What column(s) would you add?
Note: using the datatables export, visible columns are exported, and current filters are applied. What you export, is what you are currently viewing. This is helpful and intuitive. However, breaking server status out to its own column is less than ideal in my opinion, and there are multiple pools each with multiple nodes, so we can't really break those out into a column.

**Comment by epacke** [comment]
Agreed. Either we'd break the atomicity of the cell or we'd have to have one row per member. I don't see a good way to do it either. Have you had any use for this feature btw? I always point people to the actual report.

I imagine it could make sense for ie. external auditing, but rather than investing time in trying to solve the needs for each invididual use case I'd rather focus on other development areas. :)

**Comment by timriker** [comment]
I have pointed people to the actual json files if they need that level of detail. I do have people running reports with that data.
